(defun increment-number-at-point ()
  (interactive)
  (insert "(1+ ")
  (search-forward-regexp "[^0-9]")
  (backward-char)
  (insert ")")
  (eval-and-replace))

(defun add-table-line-readjust-formula ()
  "This function is very specific to one specific org-mode table I work on"
  (interactive)
  (end-of-line)
  (org-return)
  (insert "|")
  (let ((currpos (point)))
    (org-cycle)
    (search-forward "#+TBLFM")
    (search-forward "::@")
    (increment-number-at-point)
    (search-forward "..@")
    (increment-number-at-point)
    (org-ctrl-c-ctrl-c)
    (goto-char (1+ currpos))))
