;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(move-line-down
                               move-line-up
                               forward-paragraph
                               delete-blank-lines
                               c-electric-slash
                               eval-and-replace
                               back-to-indentation-or-beginning
                               magit-stage-item
                               change-outer
                               markdown-enter-key
                               orgtbl-self-insert-command
                               duplicate-current-line-or-region
                               org-delete-backward-char
                               org-self-insert-command
                               org-metaright
                               org-metaleft
                               save-region-or-current-line
                               kill-region-or-backward-word
                               change-number-at-point
                               dired-back-to-start-of-files
                               yank-indented
                               wrap-region-trigger
                               yas/expand
                               org-shiftright
                               sgml-slash
                               slime-space
                               js2-beginning-of-line
                               js2-end-of-line
                               js2-insert-and-indent
                               js2r-inline-var
                               c-electric-delete-forward
                               c-electric-backspace
                               c-electric-paren
                               c-electric-semi&comma))

(setq mc/cmds-to-run-once '(quit-window
                            eval-expression
                            toggle-read-only))

                            
                               